### ISSUE TITLE
Server setup error on initial creation

### ISSUE THREAD

**Issue by coreyshuman** [Shift3/react-technical-project#13]
npm setup/ install issue?

```
server_1    | [nodemon] 1.19.1
server_1    | [nodemon] to restart at any time, enter `rs`
server_1    | [nodemon] watching: *.*
server_1    | [nodemon] starting `node index.js`
server_1    | internal/modules/cjs/loader.js:670
server_1    |     throw err;
server_1    |     ^
server_1    | 
server_1    | Error: Cannot find module 'express'
server_1    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
server_1    |     at Function.Module._load (internal/modules/cjs/loader.js:591:27)
server_1    |     at Module.require (internal/modules/cjs/loader.js:723:19)
server_1    |     at require (internal/modules/cjs/helpers.js:14:16)
server_1    |     at Object.<anonymous> (/home/node/server/index.js:1:17)
server_1    |     at Module._compile (internal/modules/cjs/loader.js:816:30)
server_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
server_1    |     at Module.load (internal/modules/cjs/loader.js:685:32)
server_1    |     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
server_1    |     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
server_1    | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Fleury14** [comment]
I believe I've figured it out. Gonna test it out on another machine.
